### ISSUE TITLE
user roles

### ISSUE THREAD

**Issue by devmount** [devmount/SongDrive#15]
- [x] implement different user access restrictions:
- admin
- editor
- performer
- reader
- [x] implement corresponding firebase rules
- [x] test roles for current firebase rules

Permissions:

`RPEA`
`XXXX` see dashboard, song list and setlist list
`XXXX` open single songs (present, tune, export)
`XXXX` open single setlists (present, copy, export)
`-XXX` create and edit setlists
`-XXX` custom tuning in setlists
`-XXX` sync setlists
`--XX` create and edit songs
`--XX` delete songs and setlists
`---X` create, edit and delete tags
`---X` create, edit and delete users

**Comment by EinEnton** [comment]
There are basically two ways to implement this: 
- Splitting it in a multi tier application (e.g. node.js backend and frontend, a read only standalone frontend would still be possible)
- Creating an Admin SDK based tool and introduce custom claims to the Firebase authenticated users

Both require at least one different app for administrative access.

**Comment by devmount** [comment]
@EinEnton Thank you for your suggestions (and sorry for the late answer)! I would like to keep it as simple/maintainable as possible. For now, I thought of a solution with simply defining different roles in a field in firestore and build corresponding security rules in the firebase console to secure the data (https://firebase.google.com/docs/rules/get-started).
