### ISSUE TITLE
config.contact.emai is undefined in UserUnverified.vue when email is not verified

### ISSUE THREAD

**Issue by working-name** [devmount/SongDrive#195]
**Describe the bug**
When you don't have any users with a verified email and you try to log in, `config.contact.email` does not exist.

https://github.com/devmount/SongDrive/blob/d98619e0a3770fb2098fb29657c46fe39328bfa6/src/partials/UserUnverified.vue#L9

One possible way to handle it might be to make it optional

```vue
<div v-if="ready.config && config?.contact?.email">
```

Once that was in place I was given the option to resend the verification email.

- [ ] properly handle missing `config.contact.email`
- [ ] add admin notification area for missing config entries (can be used later for all kinds of messages to the admin)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 pro 22H2
 - Browser: Brave
 - Version: Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)](https://brave.com/latest/)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by devmount** [comment]
Hi Alan, thank you for this report! `config.contact.email` is a general app parameter which should be set directly in Firestore when setting up SongDrive. It is part of the https://github.com/devmount/SongDrive/blob/main/demo.import.json (as an example).

Later it can be changed in the admin settings:

![image](https://github.com/devmount/SongDrive/assets/5441654/ad7f76e0-4543-4c19-b61a-2884dac983d6)


I will add a fix nevertheless as well as a notification for admins, when there is a missing config entry, when this email address isn't set. Thanks again!

**Comment by working-name** [comment]
Oh, I see, I apologize, wrong assumption. 

I tried setting that after logging in but the UI gives an error notification and does not set it:

```c++
not-found
No document to update: projects/singyourheartout/databases/(default)/documents/config/contact
```

So I guess I should have imported the demo anyway, just to have the whole schema created?

**Comment by devmount** [comment]
No you're totally right, this isn't even mentioned in the readme. I'll fix this and complete the installation instructions. Again, thanks for the report!

**Comment by devmount** [comment]
Added a fix. Let me know if you find anything else. I guess not many people completed the whole installation process yet, so your feedback is really valuable.
