### ISSUE TITLE
Very low contrast on interactive elements

### ISSUE THREAD

**Issue by maettig** [devmount/SongDrive#44]
Some of the interactive elements in the app have a very low contrast.
* Some buttons use `#5E6769` on `#222627`. That's a contrast ratio of 2.63:1, way below the recommended 4.5:1.
* The contrast of the placeholder text in the login form is even lower.
* The contrast of elements like the "KONTO" heading is 3.15:1. Better, but could be improved as well.

Example screenshot:
![Screenshot from 2021-03-21 16-02-34](https://user-images.githubusercontent.com/1177987/111909806-ffe9bf80-8a5e-11eb-87b6-3ea832f99117.png)

The suggestion is to increase the brightness of the font color, while leaving the background colors unchanged. I believe this would greatly improve the legibility especially in a bright environment (think of the sun shining on your tablet). https://webaim.org/resources/contrastchecker/ is a great tool to check the color contrast. Personally and based on experience I suggest to aim for AA, not AAA.

**Comment by devmount** [comment]
Thank you for this report - totally agree with all of your points. A lighter text color will be a quick and easy way to increase accessibility here.
SongDrive was designed in dark mode, but a light theme is also planned for bright environments.

**Comment by devmount** [comment]
This is now implemented with #66:

- `6.37:1` and `6.07:1` for text in divider elements in main and secondary sidebar
- `5.31:1` for secondary buttons
- `4.36:1` for input placeholder

and some other elements with gray text.
