### ISSUE TITLE
Firts appearance on (very narrow) phone screens

### ISSUE THREAD

**Issue by maettig** [devmount/SongDrive#46]
On very narrow screens (like an actual phone) the home screen might look like this:
![Screenshot from 2021-03-21 16-27-13](https://user-images.githubusercontent.com/1177987/111910783-14c85200-8a63-11eb-909b-0280cdb54a15.png)

While there is nothing wrong with this, I believe it can be improved with relatively little effort. The idea is to use a media query to dramatically scale these fonts down the moment the screen is to narrow.

I played around with the CSS in the browser's console to demonstrate what I mean:
![Screenshot from 2021-03-21 16-32-34](https://user-images.githubusercontent.com/1177987/111910785-15f97f00-8a63-11eb-9b15-c7f8fc18443d.png)

**Comment by devmount** [comment]
Two column layout for the featured tiles - totally agreed.
