### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by designlook** [devmount/SongDrive#70]
**Is your feature request related to a problem? Please describe.**
Would be nice upgrading to latest VueJS

**Describe the solution you'd like**
Latest VueJS v3 and Quasar instead of Spectre CSS because Quasar have better components and support for mobile

**Describe alternatives you've considered**

**Additional context**

**Comment by devmount** [comment]
Thanks a lot @designlook for this useful suggestion and your support! 👏🏻

Upgrading to Vue 3 and using its composition API is definitely on my to-do list for a major release next year.

I see the benefits of using a framework like Quasar - I will have to evaluate if a switch is worth the effort. SongDrive is already fully responsive but I admit that it's working way better on tablets and desktops then it does on mobiles. I'll let you know my decision.

**Comment by devmount** [comment]
I decided to keep the current CSS framework and focus on the migration to Vue3 for now. Maybe in a later step, I consider migrating to another frontend framework, but for now it's not worth the effort.

**Comment by devmount** [comment]
SongDrive now runs on Vue3 with composition API.
